spring:
  application:
    name: carrito_service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/tienda_carrito?serverTimezone=UTC
    username: root
    password: ""
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: https://eureka-server:8761/eureka